### ISSUE TITLE
KeyNotFoundException thrown when Metrics Route is Missing

### ISSUE THREAD

**Issue by TaffarelJr** [AppMetrics/AppMetrics#191]
I'm getting an exception from inside AppMetrics when I try to test a custom endpoint on my WebAPI:

```
System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.AspNetCore.Http.HttpContextExtensions.GetMetricsCurrentRouteName(HttpContext context)
   ...
```

This particular custom endpoint basically just calls the `/health` endpoint in AppMetrics, and then reduces the output to a single pass/fail value. I'm guessing it has something to do with the fact that the AppMetrics endpoint is getting called even though it wasn't the originally requested endpoint.

While I'm not familiar with the internal mechanics of this method and its uses, I figure a simple dictionary check should be sufficient to fix it since it already returns a default value when the current route name is not present.

**Comment by alhardy** [comment]
@TaffarelJr Thanks for the taking the time to fix that. I'll push out a new release sometime today
