### ISSUE TITLE
App.Metrics doesn't work together with PostSharp

### ISSUE THREAD

**Issue by rmszc81** [AppMetrics/AppMetrics#212]
I'm facing a problem between these 2 frameworks.

How to reproduce the problem:

```
using System;
using App.Metrics;

namespace Metrics.src.Common.Interfaces
{
    //using Enumerators;
    public interface IApdex
    {
        String Name { get; set; }
        Unit MeasurementUnit { get; set; }
        Boolean AllowWarmup { get; set; }
        Double ApdexTSeconds { get; set; }
        String Context { get; set; }
        Boolean ResetOnReporting { get; set; }

        Boolean Track(Action action);
        Boolean Reset();
    }
}
```

The error is:

```
Severity    Code    Description Project File    Line    Suppression State
Error       Unhandled exception (postsharp-net40-x86-srv.exe release | .NET Framework 4.6.1): PostSharp.Sdk.CodeModel.BindingException: Ambiguous assembly binding policies: Assembly 'system.runtime, version=4.0.0.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a' redirects both to 'system.runtime, version=4.1.2.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a' and 'system.runtime, version=4.0.20.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a'.
   at PostSharp.Sdk.CodeModel.AssemblyBindingPolicyManager.EvaluatePolicy(IAssemblyName assemblyName, Boolean evaluateSystemPolicies)
   at PostSharp.Sdk.CodeModel.CompareExtensions.^4+F3cylo(IAssemblyName _0, IAssemblyName _1, AssemblyBindingPolicyManager _2, BindingOptions _3, Boolean _4)
   at PostSharp.Sdk.CodeModel.ModuleDeclaration.FindAssembly(IAssemblyName assemblyName, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.ModuleDeclaration.^nQbUijLO(String _0, IAssemblyName _1, BindingOptions _2)
   at PostSharp.Sdk.CodeModel.ModuleDeclaration.FindType(Type reflectionType, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.DeclarationCache.^pFnf8wEt()
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.get_TypeIdentifier()
   at PostSharp.Sdk.CodeModel.CompareExtensions.DefinitionMatchesReference(INamedType definition, INamedType reference, BindingOptions options)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.^A9yFoe2uB3TC(ITypeSignature _0, BindingOptions _1)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.MatchesReference(ITypeSignature reference)
   at PostSharp.Sdk.CodeModel.Collections.CustomAttributeDeclarationCollection.Contains(IType type)
   at PostSharp.Sdk.Extensibility.Tasks.MulticastAttributeTask.^SgrhoGlQ(AssemblyRefDeclaration _0)
   at PostSharp.Sdk.Extensibility.Tasks.MulticastAttributeTask.^+GwnKh4ZYHu3()
   at PostSharp.Sdk.Extensibility.Tasks.MulticastAttributeTask.Execute()
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Sdk.Extensibility.Project.Execute()
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.InvokeProject(ProjectInvocation projectInvocation). Metrics     
```

Is there any way to get these 2 guys working together? Anyone faced this before?

Thanks a lot.

**Comment by alhardy** [comment]
Sorry that doesn't give me much info, plus the stacktrace doesn't show anything related to App Metrics

**Comment by rmszc81** [comment]
I solved this problem, it wasn't a problem from app.metrics but from postsharp itself.

BTW, any plans on where to release 2.0?

Thanks a lot!

@rmszc81

**Comment by alhardy** [comment]
I'm looking for the time to get 2.0 out the door. just a busy time atm, hopefully soon
