### ISSUE TITLE
Using [ApiVersionNeutral] causes a null reference exception

### ISSUE THREAD

**Issue by alexquintero** [AppMetrics/AppMetrics#254]
This is with version 2.0.0 of all of the relevant App.Metrics packages.

Exception output:
```System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteTemplateResolver.ExtractRouteTemplate(RouteData routeData, ActionDescriptor actionDescriptor) in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Mvc\MvcRouteTemplateResolver.cs:line 74
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteTemplateResolver.<ResolveMatchingTemplateRouteAsync>d__6.MoveNext() in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Mvc\MvcRouteTemplateResolver.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Filters.MetricsResourceFilter.<OnResourceExecutionAsync>d__3.MoveNext() in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Mvc\MetricsResourceFilter.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

Reproduction steps:

* Simply create a controller leveraging the Microsoft.AspNetCore.Mvc.Versioning package and add the attribute `[ApiVersionNeutral]` to the class. 
* Add `services.AddMvc().AddMetrics();` to your Starup.cs in the ConfigureServices method.
* Run the application and the exception will be encountered when trying to access that endpoint.

**Comment by alhardy** [comment]
@alexquintero should your [PR](https://github.com/AppMetrics/AspNetCore/pull/23) close this issue?

**Comment by alexquintero** [comment]
@alhardy, yes it should resolve it.
