### ISSUE TITLE
App.Metrics.Reporting.Graphite 

### ISSUE THREAD

**Issue by Stu-P** [AppMetrics/AppMetrics#279]
I'm using App.Metrics with aspnet core2.0 and the graphite reporter. The latest version of App.Metrics (2.1) seems to break App.Metrics.Reporting.Graphite version 2.0.1. Reverting to App.Metrics to 2.0 and it works OK

getting the below exception with AppMetrics 2.1
```
Method not found: 'Void App.Metrics.GeneratedMetricNameMapping..ctor(System.Collections.Generic.IDictionary2<App.Metrics.HistogramValueDataKeys,System.String>, System.Collections.Generic.IDictionary2<App.Metrics.MeterValueDataKeys,System.String>, System.Collections.Generic.IDictionary2<App.Metrics.ApdexValueDataKeys,System.String>, System.Collections.Generic.IDictionary2<App.Metrics.CounterValueDataKeys,System.String>)'.
 
at App.Metrics.Formatters.Graphite.MetricsGraphitePlainTextProtocolOptions..ctor()
at App.Metrics.Formatters.Graphite.MetricsGraphitePlainTextProtocolOutputFormatter..ctor() in C:\\projects\\graphite\\src\\App.Metrics.Formatters.Graphite\\MetricsGraphitePlainTextProtocolOutputFormatter.cs:line 22   
at DinkumCoin.Api.Program.<>c.<Main>b__0_4(MetricsReportingGraphiteOptions options) in /Users/stuart/workspace/dinkum-coin-api/src/DinkumCoin.Api/Program.cs:line 41   
at App.Metrics.MetricsGraphiteReporterBuilder.ToGraphite(IMetricsReportingBuilder metricReporterProviderBuilder, Action1 setupAction) in C:\\projects\\graphite\\src\\App.Metrics.Reporting.Graphite\\Builder\\MetricsGraphiteReporterBuilder.cs:line 67   
at DinkumCoin.Api.Program.<>c.<Main>b__0_0(IMetricsBuilder builder) in /Users/stuart/workspace/dinkum-coin-api/src/DinkumCoin.Api/Program.cs:line 34
at Microsoft.AspNetCore.Hosting.MetricsAspNetWebHostBuilderExtensions.<>c__DisplayClass1_0.<ConfigureMetricsWithDefaults>b__0(WebHostBuilderContext context, IServiceCollection services) in C:\\projects\\aspnetcore\\src\\App.Metrics.AspNetCore.Hosting\\MetricsAspNetWebHostBuilderExtensions.cs:line 35
at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at DinkumCoin.Api.Program.Main(String[] args) in /Users/stuart/workspace/dinkum-coin-api/src/DinkumCoin.Api/Program.cs:line 28

```

This is when attaching the reporter like so

```
            new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseUrls("http://*:5000")
                .UseKestrel()
                .ConfigureMetricsWithDefaults(builder =>
                {
                    builder.Report.ToGraphite("net.udp://127.0.0.1:2003", TimeSpan.FromSeconds(5));
                })
                .UseStartup<Startup>()
                .UseMetrics()
etc etc
```

**Comment by alhardy** [comment]
Thanks, will have a look

**Comment by mleyb** [comment]
I seem to be having the same issue with the Elasticsearch reporter too

**Comment by theazyfa** [comment]
+1 
I confirm I just run into the same problem with Elasticsearch Reporter 
`
Method not found: 
'Void App.Metrics.GeneratedMetricNameMapping..ctor(System.Collections.Generic.IDictionary'2<App.Metrics.HistogramValueDataKeys,System.String>, System.Collections.Generic.IDictionary'2<App.Metrics.MeterValueDataKeys,System.String>, System.Collections.Generic.IDictionary'2<App.Metrics.ApdexValueDataKeys,System.String>, System.Collections.Generic.IDictionary'2<App.Metrics.CounterValueDataKeys,System.String>)'.
`

**Comment by claudiuconstantin** [comment]
Same here with ElasticSearch reporter:
`Method not found: 'Void App.Metrics.GeneratedMetricNameMapping..ctor(System.Collections.Generic.IDictionary'2, System.Collections.Generic.IDictionary'2, System.Collections.Generic.IDictionary'2, System.Collections.Generic.IDictionary'2)'`

Stack trace:
`at App.Metrics.Formatters.Elasticsearch.MetricsElasticsearchDocumentFormattingOptions..ctor()
at App.Metrics.Formatters.Elasticsearch.MetricsElasticsearchOutputFormatter..ctor(String elasticsearchIndex)
at App.Metrics.Reporting.Elasticsearch.ElasticsearchReporter..ctor(MetricsReportingElasticsearchOptions options, IElasticsearchClient elasticsearchClient)
at App.Metrics.MetricsElasticsearchReporterBuilder.ToElasticsearch(IMetricsReportingBuilder metricReporterProviderBuilder, String url, String elasticsearchIndex)
at Service.App_Start.IoC.SimpleInjectorConfig.<>c.<RegisterAppMetrics>b__8_0() in C:\dev\...\SimpleInjectorConfig.cs:line 136`

Package versions:
_"App.Metrics" Version="2.1.0"
"App.Metrics.Formatters.ElasticSearch" Version="2.0.0-alpha"
"App.Metrics.Reporting.Elasticsearch" Version="2.0.0-alpha"_

**Comment by alhardy** [comment]
Fixed in latest version
