### ISSUE TITLE
Service crash on start

### ISSUE THREAD

**Issue by omerlh** [AppMetrics/AppMetrics#289]
Hey
A very weird issue: my service is crash only when it is running on Docker, with the following error - which seems to be related to app metrics:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'App.Metrics.Internal.DefaultMetricContextRegistry' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: method
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at System.Runtime.CompilerServices.CallSite`1.CreateCustomNoMatchDelegate(MethodInfo invoke)
   at System.Runtime.CompilerServices.CallSite`1.MakeUpdateDelegate()
   at System.Runtime.CompilerServices.CallSite`1.GetUpdateDelegate(T& addr)
   at System.Runtime.CompilerServices.CallSite`1.Create(CallSiteBinder binder)
   at App.Metrics.Logging.LogProvider.get_CurrentLogProvider()
   at App.Metrics.Logging.LogProvider.GetLogger(String name)
   at App.Metrics.Internal.DefaultMetricContextRegistry..cctor()
   --- End of inner exception stack trace ---
   at App.Metrics.Internal.DefaultMetricContextRegistry.<>c__DisplayClass16_0`1.<Apdex>b__0()
   at App.Metrics.Internal.DefaultMetricContextRegistry.MetricMetaCatalog`3.<>c__DisplayClass4_0.<GetOrAdd>b__0(String n)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at App.Metrics.Internal.DefaultMetricContextRegistry.MetricMetaCatalog`3.GetOrAdd(String name, Func`1 metricProvider)
   at App.Metrics.AspNetCore.Tracking.Middleware.ApdexMiddleware..ctor(RequestDelegate next, IOptions`1 trackingMiddlwareOptionsAccessor, ILogger`1 logger, IMetrics metrics)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.UseWhenExtensions.<>c__DisplayClass0_0.<UseWhen>b__0(RequestDelegate main)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at <>.Program.Main(String[] args)
Aborted
```
Any ideas?

**Comment by alhardy** [comment]
Looks like it's crashing on logging. Can you share your startup code?

**Comment by omerlh** [comment]
This is the part that configure logging:
```
public void Configure (IApplicationBuilder app, IHostingEnvironment env) {

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionMiddleware();
            }

            Log.Logger = new LoggerConfiguration ()
                .ReadFrom.Configuration (Configuration)
                .CreateLogger ();


            app.UseAuthentication();

            app.UseMvc ();
        }
```

**Comment by omerlh** [comment]
Ok after digging into LibLog code, I think the issues is because Serilog DLL is missing. I'll investigate and update.

**Comment by omerlh** [comment]
Added Serilog, but this didn't help. I'll keep investigating...

**Comment by omerlh** [comment]
I think the issue is related to `microsoft/dotnet:2.0-runtime-deps`, which was published 3 days ago. Once I've rolled back to a previous version, things started to work.

**Comment by damianh** [comment]
Can you post a repro project to github please? Thanks.

**Comment by omerlh** [comment]
it's an internal project, but I'll try to reproduce and upload a sample repo

**Comment by omerlh** [comment]
Could reproduce, will close the issue for now.
