### ISSUE TITLE
RegisterFromAssembly Get Error "Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."

### ISSUE THREAD

**Issue by laball** [AppMetrics/AppMetrics#392]
Hi , when I was use health part in 3.0 version ,I got an error "Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."

And the stacktrace is:

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at App.Metrics.Health.Extensions.DependencyInjection.Internal.HealthChecksAsServices.AddHealthChecksAsServices(IServiceCollection services, IEnumerable`1 types) in C:\projects\microsoftextensions\src\App.Metrics.Health.Extensions.DependencyInjection\Internal\HealthChecksAsServices.cs:line 27
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionHealthCheckBuilderExtensions.RegisterFromAssembly(IHealthCheckBuilder healthCheckBuilder, IServiceCollection services, DependencyContext dependencyContext) in C:\projects\microsoftextensions\src\App.Metrics.Health.Extensions.DependencyInjection\ServiceCollectionHealthCheckBuilderExtensions.cs:line 34
   at Demo.Startup.ConfigureServices(IServiceCollection services) in D:\下载\AppMetricsDemo-master\AppMetricsDemo\Demo\Startup.cs:line 82

So I debug with the source code, and find out that, is was caused by the class "DefaultHealthCheckTypeProvider" in line 25,and the reason is that,the Assembly in StaticHealthAssemblyProvider include "App.Metrics.Health.Abstractions", but at the run time,it`s "DefinedTypes" is null.

I think ,we should exclude “App.Metrics.Health.Abstractions” assembly.

**Comment by alhardy** [comment]
Refer to the [sample application](https://github.com/AppMetrics/Samples.V2/tree/master/AspNetCore2.Health.Api.QuickStart)
