### ISSUE TITLE
MvcRouteTemplateResolver crashing with ASP.NET Core MVC 3.0.0-preview4

### ISSUE THREAD

**Issue by fmauNeko** [AppMetrics/AppMetrics#422]
Hello,

In ASP.NET Core MVC 3.0 previews, the `MvcAttributeRouteHandler` class has been moved from the `Microsoft.AspNetCore.Mvc.Internal` namespace to the `Microsoft.AspNetCore.Mvc.Routing` namespace.

This class is required by the AppMetrics [`MvcRouteTemplateResolver`](https://github.com/AppMetrics/AppMetrics/blob/master/src/AspNetCore/src/App.Metrics.AspNetCore.Mvc.Core/MvcRouteTemplateResolver.cs) class, which itself has been placed in the `Microsoft.AspNetCore.Mvc.Internal` namespace.

This causes the following crash:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteTemplateResolver.ResolveMatchingTemplateRouteAsync(RouteData routeData)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteTemplateResolver.ResolveMatchingTemplateRouteAsync(RouteData routeData)
   at Microsoft.AspNetCore.Mvc.Filters.MetricsResourceFilter.OnResourceExecutionAsync(ResourceExecutingContext context, ResourceExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context, ICorsPolicyProvider corsPolicyProvider)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Have a good day !

**Comment by adamshergold** [comment]
Same issue for me

**Comment by AKTheKnight** [comment]
Any ideas on when this might make it into a nuget release? It's currently holding me back from using this in a ASP.NET Core 3 app.

Thanks

**Comment by alhardy** [comment]
@AKTheKnight I'll be publishing a pre-release sometime over the next week

**Comment by bardagadvergur** [comment]
I am getting this issue using 3.2.0-dev0002 of App.Metrics with the latest preview of .net core 3.0. Should this be fixed already?

**Comment by fmauNeko** [comment]
@bardagadvergur You need to get a newer dev version from MyGet: https://www.myget.org/feed/appmetrics/package/nuget/App.Metrics.AspNetCore.Mvc. 3.2.0-dev0022 works fine with the latest preview8.

**Comment by bardagadvergur** [comment]
Thanks @fmauNeko ! Didn't realize there was a different package repo.

**Comment by falvarez1** [comment]
This doesn't fix the problem with Asp.Net Core 3.0 release.
