### ISSUE TITLE
MetricsPrometheusTextOutputFormatter - Synchronous operations are disallowed.

### ISSUE THREAD

**Issue by msschl** [AppMetrics/AppMetrics#511]
The MetricsPrometheusTextOutputFormatter doesn't satisfy AllowSynchronousIO option of Kestrel server

```cs
services.AddMetricsEndpoints(builder => {
    builder.MetricsTextEndpointEnabled = false;
    builder.EnvironmentInfoEndpointEnabled = false;
    builder.MetricsEndpointEnabled = true;
    builder.MetricsEndpointOutputFormatter = new MetricsPrometheusTextOutputFormatter();
});
```

```
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.Write(Stream destination, IEnumerable`1 metrics, NewLineFormat newLine)
   at App.Metrics.Formatters.Prometheus.MetricsPrometheusTextOutputFormatter.WriteAsync(Stream output, MetricsDataValueSource metricsData, CancellationToken cancellationToken)
   at App.Metrics.AspNetCore.Endpoints.Middleware.MetricsEndpointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Versions:
App.Metrics 4.0.0-preview1.0.3
App.Metrics.Formatters.Prometheus 4.0.0-preview1.0.3

**Comment by msschl** [comment]
There is an open pull request for this issue #507
