### ISSUE TITLE
Synchronous operations are disallowed in EnvInfoMiddleware and MetricsEndpointMiddleware

### ISSUE THREAD

**Issue by czd890** [AppMetrics/AppMetrics#528]
Version: `4.0.0-preview1.0.3`
`/metrics` is ok.
`/metrics-text` and `/metrics` throw exceptions.
```log
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLTP0CM7OINB", Request id "0HLTP0CM7OINB:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at App.Metrics.Formatters.Ascii.EnvInfoTextWriter.Dispose(Boolean disposing)
   at App.Metrics.Formatters.Ascii.EnvInfoTextWriter.Dispose()
   at App.Metrics.Formatters.Ascii.EnvInfoTextOutputFormatter.WriteAsync(Stream output, EnvironmentInfo environmentInfo, CancellationToken cancellationToken)
   at App.Metrics.AspNetCore.DefaultEnvResponseWriter.WriteAsync(HttpContext context, EnvironmentInfo environmentInfo, CancellationToken token)
   at App.Metrics.AspNetCore.Endpoints.Middleware.EnvInfoMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 77.6828ms 500
```

```log
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLTP0CM7OINE", Request id "0HLTP0CM7OINE:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at App.Metrics.Formatters.Ascii.MetricsTextOutputFormatter.WriteAsync(Stream output, MetricsDataValueSource metricsData, CancellationToken cancellationToken)
   at App.Metrics.AspNetCore.Endpoints.Middleware.MetricsEndpointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
```

**Comment by ianlet** [comment]
Looks like I have the same issue while accessing `/metrics`:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLU22NA5TABC", Request id "0HLU22NA5TABC:00000008": An unhandled exception was thrown by the application.
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at Newtonsoft.Json.JsonTextWriter.CloseBufferAndWriter()
   at Newtonsoft.Json.JsonTextWriter.Close()
   at Newtonsoft.Json.JsonWriter.Dispose(Boolean disposing)
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at App.Metrics.Formatters.Json.MetricsJsonOutputFormatter.WriteAsync(Stream output, MetricsDataValueSource metricData, CancellationToken cancellationToken)
   at App.Metrics.AspNetCore.DefaultMetricsResponseWriter.WriteAsync(HttpContext context, MetricsDataValueSource metricsData, CancellationToken token)
   at App.Metrics.AspNetCore.Endpoints.Middleware.MetricsEndpointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

We're using AspNetCore 3.1, could it be the issue?

**Comment by grounzero** [comment]
After having the same issue I got it working by setting `AllowSynchronousIO = true` in  `KestrelServerOptions`

i.e: 

```
.ConfigureWebHostDefaults(webBuilder =>
    webBuilder.UseKestrel((builderContext, options) => options.AllowSynchronousIO = true));
```

**Comment by NicolasReyDotNet** [comment]
@alhardy 

Hi, does the 4.0.0 nuget package have the #533 fix ?
I have the following packages 
```
    <PackageReference Include="App.Metrics.AspNetCore.Endpoints" Version="4.0.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Tracking" Version="4.0.0" />
    <PackageReference Include="App.Metrics.Extensions.DependencyInjection" Version="4.0.0" />
    <PackageReference Include="App.Metrics.Extensions.Hosting" Version="4.0.0" />
```

And I get the same error (**Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead**) on calling `/metrics-text` and `/metrics `

Should we apply @grounzero solution ? I hope we should avoid it ...

**Comment by alhardy** [comment]
It should, could you try the latest 4.1.0 preview

**Comment by NicolasReyDotNet** [comment]
@alhardy 
I moved to version 4.1.0 (not preview one)
```
    <PackageReference Include="App.Metrics.AspNetCore.Endpoints" Version="4.1.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Tracking" Version="4.1.0" />
    <PackageReference Include="App.Metrics.Extensions.DependencyInjection" Version="4.1.0" />
    <PackageReference Include="App.Metrics.Extensions.Hosting" Version="4.1.0" />
```

Here is the error I got on hitting the /metrics-text route (both /metrics and /env did not produce any I/O error). Note that even if the /metric-text route produce this exception, it still provide an expected output.

![image](https://user-images.githubusercontent.com/37657851/85419701-b2453280-b572-11ea-88fc-aff400193b26.png)

In the Configure method (Startup.cs) I use the following extension method 
```
        public static IApplicationBuilder UseAllMetricsMiddleware(this IApplicationBuilder app)
        {
            // Routes 
            // /metrics
            // /metrics-text
            // /env
            app.UseMetricsAllMiddleware();
            app.UseMetricsAllEndpoints();
            return app;
        }
```
Used here 
```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseHttpsRedirection();
            app.UseRouting();
            app.UseAuthorization();
            app.UseAllMetricsMiddleware();
          .....
```
And in the ConfigureServices method (Startup.cs) I use the following extension method 
```
        public static IServiceCollection AddAllMetrics(this IServiceCollection services)
        {
            services.AddMetrics();
            services.AddMetricsTrackingMiddleware();
            services.AddMetricsEndpoints();
            services.AddMetricsReportingHostedService();

            return services;
        }
```
Used here 
```
public void ConfigureServices(IServiceCollection services)
{
         services.AddAllMetrics();
          .....
```
Do you see any mistake explaining the behavior ?

**Comment by JianweiChen2021** [comment]
Still seeing this error with "/metrics-text" ("/metrics" and "/env" are both OK) with App.Metrics 4.2.0

**Comment by JerrettDavis** [comment]
Confirming that I still see this error using `/metrics-text`, while both `/metrics` and `/env` are fine in App.Metrics 4.3.0.
