### ISSUE TITLE
Too many failures when attempting to write to udp://localhost:8094, circuit is open   

### ISSUE THREAD

**Issue by kishorekittu76** [AppMetrics/AppMetrics#556]
When we   are working with AppMetrcis in our dotnet core micro services  getting Too many failures when attempting to write to udp://localhost:8094, circuit is open: issue 
Could you please help  me to get rid of this exception 
var metrics = new MetricsBuilder()
            .Configuration.Configure(
            options =>
            {
                options.WithGlobalTags((globalTags, info) =>
                {
                    globalTags.Add("app", "RepairApp");
                    globalTags.Add("env", "stage");
                    globalTags.Add("server", Environment.MachineName);
                });
            })
            .Report.ToInfluxDb(
                options =>
                {
                    options.InfluxDb.BaseUri = new Uri("http://127.0.0.1:9087");
                    options.InfluxDb.Database = "RepairAppInfluxData";
                    options.InfluxDb.UserName = "System";
                    options.InfluxDb.Password = "123456";
                    options.SocketPolicy.BackoffPeriod = TimeSpan.FromSeconds(30);
                    options.SocketPolicy.FailuresBeforeBackoff = 5;
                    options.SocketPolicy.Timeout = TimeSpan.FromSeconds(10);
                    options.FlushInterval = TimeSpan.FromSeconds(5);
                })
            .Build();
        services.AddMetrics(metrics);
        services.AddMetricsReportScheduler();

**Comment by alhardy** [comment]
Your code sample shows reporting to influxdb over http?

**Comment by kishorekittu76** [comment]
Reporting to Influxdb over UDP

**Comment by kishorekittu76** [comment]
var metrics = new MetricsBuilder()                   
                            .SampleWith.SlidingWindow(512)
                        .Configuration.Configure(
                        options =>
                        {
                            options.WithGlobalTags((globalTags, info) =>
                            {
                                if (!string.IsNullOrWhiteSpace(appName))
                                    globalTags.Add("app", appName);
                                globalTags.Add("servicename", serviceName);
                                if (!string.IsNullOrWhiteSpace(dockerhost))
                                    globalTags.Add("hostname", dockerhost);
                                if (!string.IsNullOrWhiteSpace(containerid))
                                    globalTags.Add("containerid", containerid);
                                // globalTags.Add("dockerhost", containerid);
                            });
                        })
                       .Report.OverUdp(
                        options =>
                          {
                              options.SocketSettings.Address = MonitoringAppModel.InfluxDbUrl;//Udp Listening Ip
                        options.SocketSettings.Port = MonitoringAppModel.Port;
                           options.FlushInterval = TimeSpan.FromSeconds(monitoringAppModel.Interval);
                             options.MetricsOutputFormatter = formatter;
                             options.SocketPolicy = new SocketPolicy();
                          if (options.SocketPolicy == null)
                        {
                            options.SocketPolicy = new SocketPolicy();
                     }
                               options.SocketPolicy.BackoffPeriod = TimeSpan.FromSeconds(30);
                          options.SocketPolicy.FailuresBeforeBackoff = 3;
                        options.SocketPolicy.Timeout = TimeSpan.FromSeconds(10);
                          })
                        .Build();                     
                        services.AddMetrics(metrics);
                        services.AddMetricsTrackingMiddleware();
                        services.AddMetricsReportingHostedService();
                        services.AddMetricsEndpoints();
                        services.AddMvc(options => options.Filters.Add(new MonitoringAppActionFilterWebAPI(metrics))).AddMetrics();
                        
                        var scheduler = new AppMetricsTaskScheduler(TimeSpan.FromSeconds(3000),
                                async () =>
                                {                                 
                                    await Task.WhenAll(metrics.ReportRunner.RunAllAsync());//export metrics to teligraf every 5 seconds.
                                });
                        scheduler.Start();

**Comment by kishorekittu76** [comment]
Expecting Reply ASAP bcz issue i posted long back  and waiting for rply

**Comment by alhardy** [comment]
UDP was contributed a while back when I tested. I'm not using UDP in production. Not sure when I'll get to investigate this. Is this something you can debug yourself and provide a fix?

Could you provide the stack trace of the error

**Comment by kishorekittu76** [comment]
s.PubSubComponent.postCloudPUBSUB(String json)
2020-07-21 04:51:45.701 [{ SourceContext: \"App.Metrics.Reporting.Socket.Client.DefaultSocketClient\", MachineName: \"ip-10-240-130-59\" }] [ERR   ] [] udp://localhost:8094 write backoff for 30 seconds
2020-07-21 04:51:45.701 [{ SourceContext: \"App.Metrics.Reporting.Socket.SocketMetricsReporter\", MachineName: \"ip-10-240-130-59\" }] [ERR   ] [] Too many failures when attempting to write to udp://localhost:8094, circuit is open"

**Comment by kishorekittu76** [comment]
Some times getting below exception also 

[{ SourceContext: \"App.Metrics.Reporting.Socket.Client.DefaultSocketClient\", MachineName: \"ip-10-240-129-153\" }] [ERR   ] [] Failed to write to udp://localhost:8094
System.Net.Sockets.SocketException (90): Message too long
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.UdpClient.<>c.<SendAsync>b__56_0(Tuple`2 targetPackedArguments, Int32 targetBytes, Int32 targetPort, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, String hostname, Int32 port)
   at App.Metrics.Reporting.Socket.Client.SocketClient.WriteAsync(String payload, CancellationToken cancellationToken)
   at App.Metrics.Reporting.Socket.Client.DefaultSocketClient.WriteAsync(String payload, CancellationToken cancellationToken)
2020-07-21 04:51:07.580 [{ SourceContext: \"App.Metrics.Reporting.Socket.SocketMetricsReporter\", MachineName: \"ip-10-240-129-153\" }] [ERR   ] [] System.Net.Sockets.SocketException (90): Message too long
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.UdpClient.<>c.<SendAsync>b__56_0(Tuple`2 targetPackedArguments, Int32 targetBytes, Int32 targetPort, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, String hostname, Int32 port)
   at App.Metrics.Reporting.Socket.Client.SocketClient.WriteAsync(String payload, CancellationToken cancellationToken)
   at App.Metrics.Reporting.Socket.Client.DefaultSocketClient.WriteAsync(String payload, CancellationToken cancellationToken)"

**Comment by kishorekittu76** [comment]
Is it possible to add custom fields like global tags to metrics.

I want to push metrics data   like Custom Fields same as global tags .So i can filter in Granada based do query on  select with fields and where condition  using tags .This is my new requirement
