### ISSUE TITLE
System.Net.Http.HttpRequestException:  Error while copying content to a stream.

### ISSUE THREAD

**Issue by kishorekittu76** [AppMetrics/AppMetrics#614]
Hello Team ,
   Could you please do needful on below issue ,while pushing metrics data  over http  from Dot net core Application(Deployed in ECS Fargate).Quick response will be appreciated .
App.Metrics.Reporting.Http.HttpMetricsReporter\", 
MachineName: \"ip-------\" }] [ERR   ] 
[] System.Net.Http.HttpRequestException: 
Error while copying content to a stream.",
"ecs_cluster":"--------",
"ecs_task_arn":"arn:aws:ecs:us-east-1:0266:
}

Thanks,
Kishore

**Comment by kishorekittu76** [comment]
"App.Metrics.Reporting.Http.Client.DefaultHttpClient\", MachineName: \"-----\" }] [ERR   ] 
[] Failed to write to http://localhost:8093/telegraf
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at App.Metrics.Reporting.Http.Client.DefaultHttpClient.WriteAsync(String payload, MetricsMediaTypeValue mediaType, CancellationToken cancellationToken)
2020-10-19 12:28:39.322 [{ SourceContext: \"App.Metrics.Reporting.Http.HttpMetricsReporter\", MachineName: \"---\" }] [ERR   ] [] System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at App.Metrics.Reporting.Http.Client.DefaultHttpClient.WriteAsync(String payload, MetricsMediaTypeValue mediaType, CancellationToken cancellationToken)"

**Comment by alhardy** [comment]
Maybe the server closed the connection mid-stream? Don't this this is related to AppMetrics
