### ISSUE TITLE
/health endpoint doing sync write

### ISSUE THREAD

**Issue by FynZ** [AppMetrics/AppMetrics#618]
Hello,

We are in the process of updating our `AppMetrics` dependencies to `4.1.0` and it seems the `HealthCheckEndpointMiddleware` is still doing synchronous write on the `/health` endpoint (other endpoints work well). We already had trouble when migrating our app to `ASP.NET Core 3.1` and ended up allowing synchronous writes at `Kestrel` level. This was a known issue that seems to have been fixed for `4.0.0` onward (according to https://github.com/AppMetrics/AppMetrics/issues/396) but I'm still facing the issue and cannot find anything on this topic (issues or doc).

Here's the end of the StackTrace : 

```
System.InvalidOperationException
Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true.
   at Microsoft.AspNetCore.TestHost.ResponseBodyWriterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at Newtonsoft.Json.JsonTextWriter.CloseBufferAndWriter()
   at Newtonsoft.Json.JsonTextWriter.Close()
   at Newtonsoft.Json.JsonWriter.Dispose(Boolean disposing)
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at App.Metrics.Health.Formatters.Json.HealthStatusJsonOutputFormatter.WriteAsync(Stream output, HealthStatus healthStatus, CancellationToken cancellationToken)
   at App.Metrics.AspNetCore.Health.Core.DefaultHealthResponseWriter.WriteAsync(HttpContext context, HealthStatus healthStatus, CancellationToken token)
   at App.Metrics.AspNetCore.Health.Endpoints.Middleware.HealthCheckEndpointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d.MoveNext()
```

(not that this is using the `TestServer` class but the same problem happens in a real environment).

and here's our configuration:

```
.UseHealthEndpoints()
.UseMetricsWebTracking()
.UseMetrics(options =>
{
    options.EndpointOptions = endpointsOptions =>
    {
        endpointsOptions.MetricsEndpointOutputFormatter = new MetricsPrometheusProtobufOutputFormatter();
        endpointsOptions.MetricsTextEndpointOutputFormatter = new MetricsPrometheusTextOutputFormatter();
    };
});
```

Is there anything on this topic ?

Thanks.

**Comment by cyberhck** [comment]
Did you figure this out? For me potential workaround would be not to use healthcheck middleware, then write your own middleware which extends healthcheck middleware.

Can you post how you end up doing this? I don't know this myself.

**Comment by FynZ** [comment]
> Did you figure this out? For me potential workaround would be not to use healthcheck middleware, then write your own middleware which extends healthcheck middleware.
> 
> Can you post how you end up doing this? I don't know this myself.

Currently we are setting `AllowSynchronousIO` to true in Kestrel server options, but we did so when migrating to .NET Core 3.1 about a year ago and we wanted to remove this workaround while upgrade `AppMetrics` packages. This is not a blocking issue as you can tweak the `HostBuilder` directly, but if it could be async all the way the better.

**Comment by alhardy** [comment]
Health check functionality has been removed, MS have an equivalent implementation, no point App Metrics competing with that
