### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'fallbackFormatter')

### ISSUE THREAD

**Issue by Aaronontheweb** [AppMetrics/AppMetrics#645]
When working with InfluxDb, we have the following App.Metrics setup inside `Startup.cs`

```csharp
  public static void ConfigureAppMetrics(IServiceCollection services)
        {
            services.AddMetricsTrackingMiddleware();
            services.AddMetrics(b =>
            {
                var metrics = b.Configuration.Configure(o =>
                    {
                        o.GlobalTags.Add("host", Dns.GetHostName());
                        o.DefaultContextLabel = "akka.net";
                        o.Enabled = true;
                        o.ReportingEnabled = true;
                    })
                    .Report.ToInfluxDb(options =>
                    {
                        options.InfluxDb.BaseUri =
                            new Uri($"http://{Environment.GetEnvironmentVariable(InfluxDbHostEnvironmentVar)}" +
                                    $":{Environment.GetEnvironmentVariable(InfluxDbPortEnvironmentVar)}");
                        options.InfluxDb.Database = Environment.GetEnvironmentVariable(InfluxDbDbEnvironmentVar);
                        options.InfluxDb.CreateDataBaseIfNotExists = true;
                        options.InfluxDb.RetentionPolicy = "rp";
                        options.FlushInterval = TimeSpan.FromSeconds(5);
                    })
                    .Build();
            });
            services.AddMetricsReportingHostedService();
        }
```

And this produces the following exception at runtime:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'fallbackFormatter')
   at App.Metrics.AspNetCore.DefaultEnvResponseWriter..ctor(IEnvOutputFormatter fallbackFormatter, IReadOnlyCollection`1 formatters)
   at Microsoft.AspNetCore.Builder.EnvInfoApplicationBuilderExtensions.GetEnvInfoResponseWriter(IServiceProvider serviceProvider, IEnvOutputFormatter formatter)
   at Microsoft.AspNetCore.Builder.EnvInfoApplicationBuilderExtensions.<>c__DisplayClass5_0.<UseEnvInfoMiddleware>b__1(IApplicationBuilder appBuilder)
   at Microsoft.AspNetCore.Builder.UseWhenExtensions.UseWhen(IApplicationBuilder app, Func`2 predicate, Action`1 configuration)
   at Microsoft.AspNetCore.Builder.EnvInfoApplicationBuilderExtensions.UseEnvInfoMiddleware(IApplicationBuilder app, IOptions`1 endpointHostingOptionsAccessor, IOptions`1 endpointsOptionsAccessor, IEnvOutputFormatter formatter)
   at Microsoft.AspNetCore.Builder.EnvInfoApplicationBuilderExtensions.UseEnvInfoEndpoint(IApplicationBuilder app)
   at Microsoft.AspNetCore.Builder.DefaultEndpointsApplicationBuilderExtensions.UseMetricsAllEndpoints(IApplicationBuilder app)
   at Petabridge.Phobos.Web.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\Repositories\Petabridge\Petabridge.Phobos.Web.InfluxDb\src\Petabridge.Phobos.Web\Startup.cs:line 195
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Petabridge.Phobos.Web.Program.Main(String[] args) in D:\Repositories\Petabridge\Petabridge.Phobos.Web.InfluxDb\src\Petabridge.Phobos.Web\Program.cs:line 17
```

Any idea why? We're not specifying any formatters as far as I'm aware.

**Comment by Aaronontheweb** [comment]
Aha, I figured this out:

```
 // enable App.Metrics routes
app.UseMetricsAllMiddleware();
app.UseMetricsAllEndpoints();
```

Had to disable the metrics endpoints from being configured, then everything worked.
