### ISSUE TITLE
StatsD/Socket: Message too long

### ISSUE THREAD

**Issue by Aaronontheweb** [AppMetrics/AppMetrics#650]
We're seeing this error appear while working with the App.Metrics 4.2.0 beta and StatsD support:

```csharp
System.Net.Sockets.SocketException (90): Message too long
   at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
   at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.UdpClient.<>c.<SendAsync>b__56_0(Tuple`2 targetPackedArguments, Int32 targetBytes, Int32 targetPort, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, String hostname, Int32 port)
   at App.Metrics.Reporting.Socket.Client.SocketClient.WriteAsync(String payload, CancellationToken cancellationToken)
   at App.Metrics.Reporting.Socket.Client.DefaultSocketClient.WriteAsync(String payload, CancellationToken cancellationToken)
```

The issue appears to be caused by the size of the StatsD datagram, sent over UDP, being larger than what can fit into a given datagram or the buffer itself. UDP packets typically can't exceed a size greater than 65,507 bytes.

We should either:

1. Design the `StatsDFormatter` so that it emits multiple UDP datagrams that are all under 65,507 bytes in the process of its string construction (to protect the format of the outbound data, it's best to do it here, rather than inside the byte stream) or
2. Have the Socket reporter for App.Metrics log warnings when the UDP datagram sizes exceed 65,507 bytes.

**Comment by Aaronontheweb** [comment]
Possibly related: https://github.com/AppMetrics/AppMetrics/issues/553

If you get one failure because the UDP packets are too large, eventually the system will poison itself and continually try to send packets that can't be sent.

**Comment by Aaronontheweb** [comment]
So this is going to be harder than I thought:

https://github.com/AppMetrics/AppMetrics/blob/d8a9028ab44fe8ce55bacb8c8192936bf3ceabeb/src/Reporting/src/App.Metrics.Reporting.Socket/SocketMetricsReporter.cs#L62-L83

Calling `Stream.Flush` on the stream passed to the `StatsDFormatter` isn't going to do anything to ensure multiple packets are transmitted separately, and therefore the implementation options are:

1. Add an overload to `IMetricsOutputFormatter` that specifies how much data is "waiting" to be sent in this batch and allow the formatter to break that data up into multiple discrete byte arrays, and use that to work around this problem.
2. Create a custom socket reporter implementation just for StatsD which handles the chunking, although truth be told there are probably other metrics platforms that will / do have this problem too since this is a UDP problem, not a StatsD problem.
3. Replace the `MemoryStream` with a `BufferedStream`, have the socket read from it asynchronously, and then write the contents out to the network each time the buffer is written to. This would restore proper "streaming" semantics back into picture using just the `Stream` class.

Either way, the socket implementation is a bit broken as is right now - logical writes and socket I/O calls are married 1:1. That shouldn't be the case, for exactly this reason - a logical write might need to be broken down into smaller I/O calls in order for the upstream APM system to be able to accept the input.
